#!/usr/bin/env python3

import colors as c
from utils import ask

text = '''how many pancakes fit on the roof that day

My name is {name} and i enjoy {noun}. I have not taken a piture in a while and
I have since becone {plural verb}. how many pankaces fit on the roof
{answer}
'''

lines = text.splitlines()
title = lines[0]
text = "\n".join(lines[1:])
print(c.yellow + title)
words = { 
    "name" : None,
    "noun" : None,
    "plural verb" : None,
    "answer" : None
}

for keyword in words:
    words[keyword] = ask(keyword.title().rstrip('0123456789')+ ': ')

print(c.clear + text.format(**words))

