#!/usr/bin/env python3

import colors as c
import fluffy as quiz
import random 

print(c.clear + quiz.intro) 

while quiz.questions:
    question_function = random.choice(quiz.questions)
    if is_correct:
        quiz.questions.remove(question_function)
